name: Md Robin Jamal
title: Project Manager | Business Ops Strategist
location: Dhaka, Bangladesh
email: jamalmdrobin@gmail.com
linkedin: https://www.linkedin.com/in/robinjamal
about: >
  Business Operations & Product Strategy expert with experience in project management, team leadership, and implementation across tech and service firms. Passionate about streamlining systems and designing research-backed product frameworks. Over the past three years, I’ve worked across diverse teams and industries—earning trust, building value, and helping transform bold ideas into real-world outcomes. I thrive at the intersection of strategy, product, and technology, and I’m passionate about turning complexity into clarity.
  Currently, I’m on a mission to build an AI-native startup in Bangladesh—focused on creating intelligent, localized solutions that blend behavioral economics, finance, and cutting-edge AI technologies. With a foundation in business studies and a degree in Film & Media Studies, I bring a multidisciplinary approach to solving problems and scaling innovation. In my previous roles, I’ve collaborated with a software development startup as a project coordinator and business development assistant, and supported marketing, operations, and data-driven strategies at a PMO-driven agency.
  
  Core strengths:
  ☑ Market research & strategic insights
  ☑ Business development & execution
  ☑ Cross-functional project coordination
  ☑ Team leadership & agile communication

  I’m always open to collaborating on meaningful projects, especially those aiming to reshape industries or serve underserved communities through tech. Let’s connect if you’re working on something impactful, or just want to chat ideas.

skills:
  - Project Management
  - Product Research & Strategy
  - Business Process Optimization
  - Team Management
  - Market Analysis
  - SOP Design
  - Python,SQL

experience:
  
  - role: Co-Founder & COO | Implementation Strategist
    company: Relogic Solutions
    date: Apr 2025
    details:
      - Buliding an AI Native Studio 
      - Managing businees and product strategic mission as per Relogic's Vision
      - Engaged in depth product reserch and MVP development
      - Leading business, teams and all project operations

  - role: Project Coordinator & Assistant
    company: Ansys ICA
    date: Apr 2021 - Oct 2024
    details:
      - Delivered strategic consulting and operational support to enhance team performance and project outcomes
      - Directed operations, strategy, and research for inbound and outbound outreach campaigns
      - Led multiple cross-functional virtual assistant (VA) teams across diverse operational areas
      - Collaborated remotely with the web development team to support project execution and delivery
      - Managed project task boards, facilitated cross-team coordination, and conducted meetings with clients, stakeholders, and customer
      - Oversaw client communications, ensuring timely follow-ups and smooth project progression

  - role: Project & Account Management Assistant
    company: Goodman Group LLC - DBA DataTools Pro
    date: May 2024 - Jun 2024
    details:
      - Assisted the CEO in optimizing and streamlining overall business operations
      - Oversaw multiple teams and supported Project Management Office (PMO) functions to ensure organizational efficiency
      - Developed Standard Operating Procedures (SOPs) and prepared key business documentation to support scalable growth

  - role: Business Operations Specialist
    company: BizFuel
    date: Nov 2023 - Mar 2024
    details:
      - Managed client accounts and ensured consistent communication and service delivery for the agency
      - Supported the preparation and delivery of client marketing performance reports
      - Supervised and evaluated the performance of cold-calling team members to optimize outreach effectiveness
      - Executed routine administrative duties and produced ad-hoc reports as needed
      - Streamlined core business operations to improve workflow efficiency and team coordination

education:
  - degree: Bachelors in Social Sciences
    institution: University of Dhaka
    year: 2018 - 2022

certifications & trainings:
    - Python with Machine Learning - Creative IT Institute
    - Marketing Analytics
    - Business Economics
    - Data Analytics
    - Qualitative and Quantitative Research
    - Statistics
