name: Md Robin Jamal
title: Project Manager | Business Ops Strategist
location: Dhaka, Bangladesh
email: jamalmdrobin@gmail.com
linkedin: https://www.linkedin.com/in/robinjamal
about: >
  Business Operations & Product Strategy expert with experience in project management, team leadership,
  and implementation across tech and service firms. Passionate about streamlining systems and designing
  research-backed product frameworks.

skills:
  - Project Management
  - Product Research & Strategy
  - Business Process Optimization
  - Team Management
  - Market Analysis
  - SOP Design
  - Python,SQL

experience:
  
  - role: Co-Founder & COO | Implementation Strategist
    company: Relogic Solutions
    date: Apr 2025
    details:
      - Buliding an AI Native Studio 
      - Managing businees and product strategic mission as per Relogic's Vision
      - Engaged in depth product reserch and MVP development
      - Leading business, teams and all project operations

  - role: Project Coordinator & Assistant
    company: Ansys ICA
    date: Apr 2021 - Oct 2024
    details:
      - Delivered strategic consulting and operational support to enhance team performance and project outcomes
      - Directed operations, strategy, and research for inbound and outbound outreach campaigns
      - Led multiple cross-functional virtual assistant (VA) teams across diverse operational areas
      - Collaborated remotely with the web development team to support project execution and delivery
      - Managed project task boards, facilitated cross-team coordination, and conducted meetings with clients, stakeholders, and customer
      - Oversaw client communications, ensuring timely follow-ups and smooth project progression

  - role: Project & Account Management Assistant
    company: Goodman Group LLC - DBA DataTools Pro
    date: May 2024 - Jun 2024
    details:
      - Assisted the CEO in optimizing and streamlining overall business operations
      - Oversaw multiple teams and supported Project Management Office (PMO) functions to ensure organizational efficiency
      - Developed Standard Operating Procedures (SOPs) and prepared key business documentation to support scalable growth

  - role: Business Operations Specialist
    company: BizFuel
    date: Nov 2023 - Mar 2024
    details:
      - Managed client accounts and ensured consistent communication and service delivery for the agency
      - Supported the preparation and delivery of client marketing performance reports
      - Supervised and evaluated the performance of cold-calling team members to optimize outreach effectiveness
      - Executed routine administrative duties and produced ad-hoc reports as needed
      - Streamlined core business operations to improve workflow efficiency and team coordination

education:
  - degree: Bachelors in Social Sciences
    institution: University of Dhaka
    year: 2018 - 2022

certifications & trainings:
    - Python with Machine Learning - Creative IT Institute
    - Marketing Analytics
    - Business Economics
    - Data Analytics
    - Qualitative and Quantitative Research
    - Statistics